// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PodData Description of a PPCaaS Pod
//
// swagger:model PodData
type PodData struct {

	// Number of available cores in the Pod
	AvailableCores float64 `json:"availableCores,omitempty"`

	// Amount of available memory in the Pod (GB)
	AvailableMemory int64 `json:"availableMemory,omitempty"`

	// Amount of available storage in the Pod (GB)
	AvailableStorage int64 `json:"availableStorage,omitempty"`

	// ID of the Satellite Location
	SatLocationID string `json:"satLocationID,omitempty"`

	// Total number of cores in the Pod
	TotalCores float64 `json:"totalCores,omitempty"`

	// Total amount of memory in the Pod (GB)
	TotalMemory int64 `json:"totalMemory,omitempty"`

	// Total amount of storage in the Pod (GB)
	TotalStorage int64 `json:"totalStorage,omitempty"`
}

// Validate validates this pod data
func (m *PodData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pod data based on context it is used
func (m *PodData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PodData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodData) UnmarshalBinary(b []byte) error {
	var res PodData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
